package com.greendaoexample.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.greendaoexample.database.MyObject;

import com.greendaoexample.database.MyObjectDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myObjectDaoConfig;

    private final MyObjectDao myObjectDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myObjectDaoConfig = daoConfigMap.get(MyObjectDao.class).clone();
        myObjectDaoConfig.initIdentityScope(type);

        myObjectDao = new MyObjectDao(myObjectDaoConfig, this);

        registerDao(MyObject.class, myObjectDao);
    }
    
    public void clear() {
        myObjectDaoConfig.clearIdentityScope();
    }

    public MyObjectDao getMyObjectDao() {
        return myObjectDao;
    }

}
